apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: httpbin-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/solo-io/solo-blog-edge-argo-15
    targetRevision: HEAD
    path: cfg
  destination:
    server: https://kubernetes.default.svc
    namespace: default
